name: merna_bot
description: A powerful XMPP AI Bot for SyriaTalk
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0' # تم التحديث ليتناسب مع الإصدارات الحالية

dependencies:
  xmpp_stone: ^0.4.4-dev.7 # الإصدار الأحدث المتوافق مع Null Safety
  http: ^1.2.0
  html: ^0.15.6
